version: "3.8"

services:
    jxufe-csg-website:
        image: jxufe-csg-website:latest
        restart: unless-stopped
        ports:
            - "4122:3000"
        environment:
            - NODE_ENV=production
